apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaindex-rag-deployment
  namespace: default
  labels:
    app: llamaindex-rag
spec:
  selector:
    matchLabels:
      app: llamaindex-rag
  template:
    metadata:
      labels:
        app: llamaindex-rag
    spec:
      containers:
      - name: llamaindex-rag
        image: us-docker.pkg.dev/akvelon-gke-aieco/llamaindex/llamaindex-fastapi:1.0.0
        env:
        - name: MODEL_NAME
          value: "BAAI/bge-small-en-v1.5"
        - name: REDIS_URL
          value: redis://redis-stack-service
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api
              key: openai-api-key
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llamaindex-rag-service
spec:
  selector:
    app: llamaindex-rag
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
