runtime: python39

handlers:
  - url: /$
    static_files: public/index.html
    upload: public/index.html
  - url: /(.*)/$
    static_files: public/\1/index.html
    upload: public/.*/index.html
  - url: /
    static_dir: public
    secure: always
  - url: /.*
    secure: always
    script: auto