steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/${registry}/${image}', './flow/image' ]
images:
- 'us-docker.pkg.dev/$PROJECT_ID/${registry}/${image}'
