apiVersion: batch/v1
kind: Job
metadata:
  name: llamaindex-ingest-data
spec:
  template:
    spec:
      containers:
      - name: ingest-data
        image:  us-docker.pkg.dev/akvelon-gke-aieco/akamalov-llamaindex-test/llamaindex-rag-demo:latest 
        imagePullPolicy: Always
        command: ["python3", "cmd/ingest_data.py"]
        env:
        - name: MODEL_NAME
          value: BAAI/bge-small-en-v1.5
        - name: REDIS_HOST
          value: redis-stack-service
        - name: REDIS_PORT
          value: "6379"
      restartPolicy: Never
  backoffLimit: 4
