apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaindex-rag-deployment
  labels:
    app: llamaindex-rag
spec:
  selector:
    matchLabels:
      app: llamaindex-rag
  template:
    metadata:
      labels:
        app: llamaindex-rag
    spec:
      containers:
        - name: llamaindex-rag
          image: us-docker.pkg.dev/akvelon-gke-aieco/akamalov-llamaindex-test/llamaindex-rag-demo:latest
          imagePullPolicy: Always
          env:
            - name: MODEL_NAME
              value: gemma2
            - name: REDIS_HOST
              value: redis-stack-service
            - name: REDIS_PORT
              value: "6379"
            
            - name: OLLAMA_SERVER_URL
              value: http://ollama-service:11434
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llamaindex-rag-service
spec:
  selector:
    app: llamaindex-rag
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
